[package]
name = "uno"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
naia-shared = "0.10"
uuid = { version = "1.1", features = ["v4"] }
bevy_ecs = "0.7"
