[package]
name = "uno-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.78"

# Dependencies for native only.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# bevy = {version = "0.5", default-features = false, features = ["bevy_wgpu", "bevy_winit", "render", "x11"]}
bevy = "0.6"
bevy_ecs = "0.6"
bevy_egui = "0.10"
uno = { path = "../uno" }

[lib]
crate-type = ["cdylib", "rlib"]

# Dependencies for WASM only.
# [target.'cfg(target_arch = "wasm32")'.dependencies]
# bevy = { version = "0.6", default-features = false, features = ["bevy_winit", "render"] }
# bevy_egui = "0.10"
# bevy_webgl2 = "0.5"
# uno = { path = "../uno" }
